# Mirror of DejaVu\02_core\05_color.lua.
# Top-level color constants stay as same-name keys with one reverse entry.
# RGBA keys avoid collisions such as BLACK, TRANSPARENT, and C0.
COLOR_MAP: dict[str, dict[str, str]] = {'RED': {'255,0,0': 'RED'},
                                        'GREEN': {'0,255,0': 'GREEN'},
                                        'BLUE': {'0,0,255': 'BLUE'},
                                        'BLACK': {'0,0,0': 'BLACK'},
                                        'WHITE': {'255,255,255': 'WHITE'},
                                        'TRANSPARENT': {'0,0,0,0': 'TRANSPARENT'},
                                        'SPELL_TYPE': {'60,100,220': 'MAGIC',
                                                       '100,0,120': 'CURSE',
                                                       '160,120,60': 'DISEASE',
                                                       '154,205,50': 'POISON',
                                                       '230,120,20': 'ENRAGE',
                                                       '80,0,20': 'BLEED',
                                                       '255,60,60': 'DEBUFF_ON_FRIENDLY',
                                                       '80,220,120': 'BUFF_ON_FRIENDLY',
                                                       '64,158,210': 'PLAYER_SPELL',
                                                       '255,255,60': 'ENEMY_SPELL_INTERRUPTIBLE',
                                                       '200,0,0': 'ENEMY_SPELL_NOT_INTERRUPTIBLE',
                                                       '105,105,210': 'DEBUFF_ON_ENEMY',
                                                       '0,0,0,0': 'NONE'},
                                        'MARK_POINT': {'15,25,20': 'NEAR_BLACK_1', '25,15,20': 'NEAR_BLACK_2'},
                                        'C0': {'0,0,0': 'C0'},
                                        'C100': {'100,100,100': 'C100'},
                                        'C150': {'150,150,150': 'C150'},
                                        'C200': {'200,200,200': 'C200'},
                                        'C250': {'250,250,250': 'C250'},
                                        'C255': {'255,255,255': 'C255'},
                                        'ROLE': {'180,80,20': 'TANK', '120,200,255': 'HEALER', '230,200,50': 'DAMAGER', '0,0,0': 'NONE'},
                                        'CLASS': {'199,86,36': 'WARRIOR',
                                                  '245,140,186': 'PALADIN',
                                                  '163,203,66': 'HUNTER',
                                                  '255,245,105': 'ROGUE',
                                                  '196,207,207': 'PRIEST',
                                                  '125,125,215': 'DEATHKNIGHT',
                                                  '64,148,255': 'SHAMAN',
                                                  '64,158,210': 'MAGE',
                                                  '105,105,210': 'WARLOCK',
                                                  '0,255,150': 'MONK',
                                                  '255,125,10': 'DRUID',
                                                  '163,48,201': 'DEMONHUNTER',
                                                  '108,191,246': 'EVOKER'},
                                        'STATUS_BOOLEAN': {'228,70,44': 'EXISTS',
                                                           '61,143,141': 'IS_ALIVE',
                                                           '68,157,209': 'IS_ENEMY',
                                                           '90,162,73': 'CAN_ATTACK',
                                                           '83,171,67': 'IS_IN_RANGED_RANGE',
                                                           '141,98,124': 'IS_IN_MELEE_RANGE',
                                                           '18,166,115': 'IS_IN_COMBAT',
                                                           '122,35,253': 'IS_TARGET',
                                                           '242,197,44': 'IS_MOVING',
                                                           '104,198,122': 'IS_MOUNTED',
                                                           '197,87,210': 'IS_EMPOWERING',
                                                           '220,105,202': 'IS_CHAT_INPUT_ACTIVE',
                                                           '232,223,83': 'IS_SPELL_TARGETING',
                                                           '138,63,22': 'IS_IN_GROUP_OR_RAID',
                                                           '245,54,187': 'HAS_BIG_DEFENSE',
                                                           '179,75,127': 'HAS_DISPELLABLE_DEBUFF',
                                                           '15,27,193': 'TRINKET_1_USABLE',
                                                           '76,60,160': 'TRINKET_2_USABLE',
                                                           '22,233,229': 'HEALTHSTONE_USABLE',
                                                           '97,165,227': 'HEALING_POTION_USABLE',
                                                           '122,238,1': 'IS_WAITING_DELAYED_UPDATE'},
                                        'MARK_FRAME': {'214,93,177': 'PLAYER_BUFF',
                                                       '48,201,128': 'CHARGE_SPELL',
                                                       '10,76,60': 'PLAYER_DEBUFF',
                                                       '52,152,219': 'TARGET_DEBUFF',
                                                       '241,196,15': 'TARGET_STATUS',
                                                       '230,126,34': 'FOCUS_STATUS',
                                                       '155,89,182': 'MOUSEOVER_STATUS',
                                                       '39,174,96': 'SPEC',
                                                       '127,140,141': 'SETTING',
                                                       '192,57,43': 'FOCUS_DEBUFF',
                                                       '233,30,99': 'MOUSEOVER_DEBUFF',
                                                       '26,188,156': 'PLAYER_STATUS',
                                                       '243,156,18': 'PARTY1',
                                                       '142,68,173': 'PARTY2',
                                                       '22,160,133': 'PARTY3',
                                                       '211,84,0': 'PARTY4',
                                                       '255,71,87': 'SPELL_LIST_1',
                                                       '0,196,255': 'SPELL_LIST_2',
                                                       '57,255,20': 'SPELL_LIST_3',
                                                       '255,0,245': 'SPELL_LIST_4'}}
